/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-05-23 04:31:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <title>Hexashop Ecommerce HTML CSS Template</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional CSS Files -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/font-awesome.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo-hexashop.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/owl-carousel.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/lightbox.css\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("TemplateMo 571 Hexashop\r\n");
      out.write("\r\n");
      out.write("https://templatemo.com/tm-571-hexashop\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("    ");
HttpSession sn = request.getSession(false); 
      out.write("\r\n");
      out.write("    <!-- ***** Preloader Start ***** -->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <div class=\"jumper\">\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>  \r\n");
      out.write("    <!-- ***** Preloader End ***** -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- ***** Header Area Start ***** -->\r\n");
      out.write("    <header class=\"header-area header-sticky\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <nav class=\"main-nav\">\r\n");
      out.write("                        <!-- ***** Logo Start ***** -->\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"logo\">\r\n");
      out.write("                            <img src=\"assets/images/logo.png\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <!-- ***** Logo End ***** -->\r\n");
      out.write("                        <!-- ***** Menu Start ***** -->\r\n");
      out.write("                        <ul class=\"nav\">\r\n");
      out.write("                            <li class=\"scroll-to-section\"><a href=\"#top\" class=\"active\">Home</a></li>\r\n");
      out.write("                            <li class=\"scroll-to-section\"><a href=\"#men\">Men's</a></li>\r\n");
      out.write("                            <li class=\"scroll-to-section\"><a href=\"#women\">Women's</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"javascript:;\">Pages</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("                                    <li><a href=\"products.jsp\">Products</a></li>\r\n");
      out.write("                                    <li><a href=\"single-product.jsp\">Single Product</a></li>\r\n");
      out.write("                                    <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"javascript:;\">Features</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Features Page 1</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Features Page 2</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Features Page 3</a></li>\r\n");
      out.write("                                    <li><a rel=\"nofollow\" href=\"https://templatemo.com/page/4\" target=\"_blank\">Template Page 4</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                           ");
if(sn==null){ 
      out.write("\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"scroll-to-section\"><a href=\"#explore\">Explore</a></li>\r\n");
      out.write("                            <li class=\"\"><a href=\"Signup.jsp\">Sign Up</a></li>\r\n");
      out.write("                            <li class=\"\"><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                            ");
} else{
      out.write("\r\n");
      out.write("                            <li class=\"\"><a href=\"login.jsp\">Logout</a></li>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </ul>        \r\n");
      out.write("                        <a class='menu-trigger'>\r\n");
      out.write("                            <span>Menu</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <!-- ***** Menu End ***** -->\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- ***** Header Area End ***** -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
